#ifndef _PDU_INFO_H_
#define _PDU_INFO_H_

#include "pdu_ctype_UInt8.h"

#define PDU_MODELCAR_IFWINKERL_CHANNEL_ID   0
#define PDU_MODELCAR_IFWINKERR_CHANNEL_ID   1
/*
 *  TODO:今後IfLampを追加時に使用
 */
#define PDU_MODELCAR_IFLAMPBRAKE_CHANNEL_ID 2
#define PDU_MODELCAR_IFLAMPHEAD_CHANNEL_ID  3
#define PDU_MODELCAR_IFLAMPFOG_CHANNEL_ID   4
#define PDU_MODELCAR_IFLAMPBACK_CHANNEL_ID  5

#endif /* _PDU_INFO_H_ */
